[package]
name = "leakcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
twizzler = { workspace = true }
twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-rt-abi = { path = "../../abi/rt-abi" }
twizzler-runtime = { workspace = true }
monitor-api = { workspace = true }

[package.metadata]
twizzler-build = "test"
