name: 'setup'
description: 'Setup tools'
runs:
  using: "composite"
  steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20.x'
    - name: Setup llvm
      run: (wget -qO- https://apt.llvm.org/llvm.sh | bash -s -- 18) || true
      shell: bash

