repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: local
  hooks:
    - id: fmt
      name: fmt
      entry: bash -c "cargo fmt --all"
      language: system
      types: [rust]
      args: [""]
