edition = "2021"
use_field_init_shorthand = true
newline_style = "Unix"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
group_imports = "StdExternalCrate"
