[package]
name = "pager_stress_test"
version = "0.1.0"
edition = "2021"

[dependencies]
twizzler = { path = "../../lib/twizzler" }
twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-runtime = { path = "../../rt" }
clap = { version = "4.0", features = ["derive"] }
