use std::{
    fs::File,
    io::{Read, Write},
    path::Path,
    process::Command,
};

use guess_host_triple::guess_host_triple;
use toml_edit::{Array, DocumentMut};

use crate::triple::Triple;

pub fn install(triple: &Triple) -> anyhow::Result<()> {
    println!("Building rust for {}", triple);
    generate_native_config_toml(triple)?;
    build_rust(triple)
}

fn build_rust(triple: &Triple) -> anyhow::Result<()> {
    std::env::set_var("BOOTSTRAP_SKIP_TARGET_SANITY", "1");

    let status = Command::new("./x.py")
        .arg("install")
        .current_dir("toolchain/src/rust")
        .status()?;
    if !status.success() {
        anyhow::bail!("failed to compile rust toolchain");
    }

    let src_status = Command::new("./x.py")
        .arg("install")
        .arg("src")
        .current_dir("toolchain/src/rust")
        .status()?;
    if !src_status.success() {
        anyhow::bail!("failed to install rust source");
    }

    Ok(())
}

fn generate_native_config_toml(triple: &Triple) -> anyhow::Result<()> {
    /* We need to add two(ish) things to the config.toml for rustc: the paths of tools for each twizzler target (built by LLVM as part
    of rustc), and the host triple (added to the list of triples to support). */
    //TODO: make this an actual path instead of rle path
    let mut data = File::open("toolchain/src/config.toml")?;
    let mut buf = String::new();
    data.read_to_string(&mut buf)?;
    let commented =
        String::from("# This file was auto-generated by xtask. Do not edit directly.\n") + &buf;
    let mut toml = commented.parse::<DocumentMut>()?;
    let llvm_bin = Path::new("toolchain/install/bin").canonicalize()?;
    let tstr = &triple.to_string();
    let install_prefix = Path::new("toolchain/install/sysroots")
        .join(tstr)
        .join("ports/rust");
    let build_dir = Path::new("toolchain/build/ports/rust").join(tstr);
    let sysroot_dir = Path::new("toolchain/install/sysroots")
        .join(tstr)
        .canonicalize()?;

    std::fs::create_dir_all(&build_dir)?;
    let build_dir = build_dir.canonicalize()?;

    toml["build"]["target"].as_array_mut().unwrap().push(tstr);
    toml["build"]["host"]
        .as_array_mut()
        .unwrap()
        .push(guess_host_triple().unwrap());
    toml["build"]["host"].as_array_mut().unwrap().push(tstr);
    toml["install"]["prefix"] = toml_edit::value(install_prefix.display().to_string());

    let mut cc = llvm_bin
        .join("clang")
        .canonicalize()?
        .to_str()
        .unwrap()
        .to_string();
    let mut cxx = llvm_bin
        .join("clang++")
        .canonicalize()?
        .to_str()
        .unwrap()
        .to_string();
    let mut ld = llvm_bin
        .join("clang++")
        .canonicalize()?
        .to_str()
        .unwrap()
        .to_string();
    let mut ar = llvm_bin
        .join("llvm-ar")
        .canonicalize()?
        .to_str()
        .unwrap()
        .to_string();

    toml["target"][tstr]["llvm-has-rust-patches"] = toml_edit::value(true);
    toml["target"][tstr]["cc"] = toml_edit::value(cc);
    toml["target"][tstr]["cxx"] = toml_edit::value(cxx);
    toml["target"][tstr]["linker"] = toml_edit::value(ld);
    toml["target"][tstr]["ar"] = toml_edit::value(ar);

    let mut rustflags_array = Array::new();
    rustflags_array.push("-C");
    rustflags_array.push(format!("link-arg=--sysroot={}", sysroot_dir.display()));
    rustflags_array.push("-C");
    rustflags_array.push(format!("link-arg=--target={}", tstr));

    toml["target"][tstr]["rustflags"] = toml_edit::value(rustflags_array);
    toml["target"][tstr]["llvm-libunwind"] = toml_edit::value("in-tree");

    toml["build"]["target"].as_array_mut().unwrap().push(tstr);
    toml["build"]["host"].as_array_mut().unwrap().push(tstr);
    toml["build"]["build-dir"] = toml_edit::value(build_dir.display().to_string());

    let mut out = File::create("toolchain/src/rust/bootstrap.toml")?;
    out.write_all(toml.to_string().as_bytes())?;
    Ok(())
}
