[package]
name = "trace"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
ndarray-stats = "*"
ndarray = "*"

twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-rt-abi = { path = "../../abi/rt-abi" }
monitor-api = { path = "../../rt/monitor-api" }
twizzler = { path = "../../lib/twizzler" }
