use std::{
    fs::File,
    io::{Read, Write},
    path::Path,
};

use reqwest::Client;
use toml_edit::DocumentMut;

use crate::{
    toolchain::{download_file, guess_host_triple, install_build_tools, BootstrapOptions},
    triple::all_possible_platforms,
};

async fn download_efi_files(client: &Client) -> anyhow::Result<()> {
    // efi binaries for x86 machines
    download_file(
        client,
        "http://twizzler.io/dist/bootfiles/OVMF.fd",
        "toolchain/install/OVMF.fd",
    )
    .await?;
    download_file(
        client,
        "http://twizzler.io/dist/bootfiles/BOOTX64.EFI",
        "toolchain/install/BOOTX64.EFI",
    )
    .await?;
    // efi binaries for aarch64 machines
    download_file(
        client,
        "http://twizzler.io/dist/bootfiles/QEMU_EFI.fd",
        "toolchain/install/OVMF-AA64.fd",
    )
    .await?;
    download_file(
        client,
        "http://twizzler.io/dist/bootfiles/BOOTAA64.EFI",
        "toolchain/install/BOOTAA64.EFI",
    )
    .await?;

    Ok(())
}

pub fn setup_build(cli: &BootstrapOptions) -> anyhow::Result<()> {
    let client = Client::new();
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?
        .block_on(download_efi_files(&client))?;

    install_build_tools(&cli)?;

    Ok(())
}

pub fn generate_config_toml(_cli: &BootstrapOptions) -> anyhow::Result<()> {
    /* We need to add two(ish) things to the config.toml for rustc: the paths of tools for each twizzler target (built by LLVM as part
    of rustc), and the host triple (added to the list of triples to support). */
    //TODO: make this an actual path instead of rle path
    let mut data = File::open("toolchain/src/config.toml")?;
    let mut buf = String::new();
    data.read_to_string(&mut buf)?;
    let commented =
        String::from("# This file was auto-generated by xtask. Do not edit directly.\n") + &buf;
    let mut toml = commented.parse::<DocumentMut>()?;
    let host_triple = guess_host_triple().unwrap();
    let llvm_bin = Path::new("toolchain/install/bin");
    toml["build"]["target"]
        .as_array_mut()
        .unwrap()
        .push(host_triple);
    toml["build"]["host"]
        .as_array_mut()
        .unwrap()
        .push(host_triple);

    let host_cc = std::env::var("CC").unwrap_or("/usr/bin/clang".to_string());
    let host_cxx = std::env::var("CXX").unwrap_or("/usr/bin/clang++".to_string());
    let host_ld = std::env::var("LD").unwrap_or("/usr/bin/clang++".to_string());
    toml["target"][host_triple]["llvm-has-rust-patches"] = toml_edit::value(true);
    toml["target"][host_triple]["cc"] = toml_edit::value(host_cc);
    toml["target"][host_triple]["cxx"] = toml_edit::value(host_cxx);
    toml["target"][host_triple]["linker"] = toml_edit::value(host_ld);
    let llvm_config = Path::new("toolchain/install/bin/llvm-config").canonicalize()?;
    toml["target"][host_triple]["llvm-config"] =
        toml_edit::value(llvm_config.display().to_string());

    for triple in all_possible_platforms() {
        let clang = llvm_bin
            .join("clang")
            .canonicalize()?
            .to_str()
            .unwrap()
            .to_string();
        // Use the C compiler as the linker.
        let linker = llvm_bin
            .join("ld.lld")
            .canonicalize()?
            .to_str()
            .unwrap()
            .to_string();
        let clangxx = llvm_bin
            .join("clang++")
            .canonicalize()?
            .to_str()
            .unwrap()
            .to_string();
        let ar = llvm_bin
            .join("llvm-ar")
            .canonicalize()?
            .to_str()
            .unwrap()
            .to_string();
        let current_dir = std::env::current_dir().unwrap();
        let sysroot_dir = current_dir.join(format!(
            "toolchain/install/sysroots/{}/lib",
            triple.to_string()
        ));

        let tstr = &triple.to_string();
        toml["target"][tstr]["cc"] = toml_edit::value(clang);
        toml["target"][tstr]["cxx"] = toml_edit::value(clangxx);
        toml["target"][tstr]["linker"] = toml_edit::value(linker);
        toml["target"][tstr]["ar"] = toml_edit::value(ar);
        let mut ar = toml_edit::Array::new();
        ar.push("-L");
        ar.push(sysroot_dir.to_str().unwrap());

        toml["target"][tstr]["rustflags"] = toml_edit::value(ar);

        toml["target"][tstr]["llvm-has-rust-patches"] = toml_edit::value(true);
        toml["target"][tstr]["llvm-libunwind"] = toml_edit::value("in-tree");
        toml["target"][tstr]["llvm-config"] = toml_edit::value(llvm_config.display().to_string());

        toml["build"]["target"].as_array_mut().unwrap().push(tstr);
        //toml["build"]["host"].as_array_mut().unwrap().push(tstr);
    }

    let mut out = File::create("toolchain/src/rust/bootstrap.toml")?;
    out.write_all(toml.to_string().as_bytes())?;
    Ok(())
}
