[package]
name = "genrandom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-abi = { path = "../../lib/twizzler-abi", features = ["runtime"] }
getrandom = { path = "../../lib/getrandom-twizzler" }

[package.metadata]
twizzler-build = "static"
