[package]
name = "secgate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "dylib"]

[dependencies]
#ring = { version = "*", default-features = false, features = ["alloc"] }
secgate-macros = { path = "secgate-macros" }

[dev-dependencies]
twizzler-abi = { path = "../twizzler-abi", features = ["runtime"]}