[package]
name = "pager-iotop"
version = "0.1.0"
edition = "2021"

[dependencies]
twizzler = { path = "../../lib/twizzler" }
twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-runtime = { path = "../../rt" }
pager-srv = { path = "../../srv/pager-srv" }

