//! A memory context is the primary abstraction the kernel uses for manipulating whatever memory
//! system this machine has. This includes both kernel memory management (kernel memory allocator)
//! and management of userland resources. The rest of the kernel can interact with the functions in
//! [UserContext] to operate on userland-visible memory state (e.g. objects' slots mappings in x86),
//! and the functions in [KernelMemoryContext] to operate on kernel memory state (e.g. the allocator
//! and kernel mappings in the higher-half on x86).

use alloc::sync::Arc;
use core::{alloc::Layout, ptr::NonNull};

use twizzler_abi::{
    device::CacheType,
    object::{ObjID, Protections},
    syscall::MapFlags,
};
use twizzler_rt_abi::error::TwzError;

use self::virtmem::KernelObjectVirtHandle;
use crate::{obj::ObjectRef, once::Once, syscall::object::ObjectHandle};

impl ObjectHandle for ContextRef {
    type HandleType = Context;
}

pub mod virtmem;

/// The context type for this system (e.g. [virtmem::VirtContext] for x86).
pub type Context = virtmem::VirtContext;
/// The [Context] type wrapped in an [Arc].
pub type ContextRef = Arc<Context>;

/// A trait that defines the operations expected by higher-level object management routines. An
/// architecture-dependent type can be created that implements Context, which can then be used by
/// the rest of the kernel to manage objects in a context (e.g. an address space).
pub trait UserContext {
    /// The type that is expected for informing the context how to map the object (e.g. a slot
    /// number).
    type MappingInfo;

    /// An opaque handle to whatever [Self::switch_to] would load (e.g. a page-table root), for
    /// callers that switch often enough to want to cache the lookup.
    type SwitchTarget: Copy;

    /// Switch to this context.
    fn switch_to(&self, sctx: ObjID);

    /// What [Self::switch_to] would load for `sctx`, if it is registered in this context.
    fn switch_target(&self, sctx: ObjID) -> Option<Self::SwitchTarget>;

    /// Switch to a target previously obtained from [Self::switch_target].
    ///
    /// # Safety
    /// The target must have come from [Self::switch_target] on this context, and the security
    /// context it belongs to must still be registered here. Holding a reference to that security
    /// context is what guarantees the latter: the registration is torn down by
    /// `SecurityContext::drop`.
    unsafe fn switch_to_target(&self, target: &Self::SwitchTarget);
    /// Insert a range of an object into the context. The implementation may choose to use start and
    /// len as hints, but should keep in mind that calls to `insert_object` may be generated by
    /// faults, and so should strive to resolve the fault by correctly mapping the object as
    /// requested.
    fn insert_object(
        self: &Arc<Self>,
        mapping_info: Self::MappingInfo,
        object_info: &ObjectContextInfo,
    ) -> Result<(), TwzError>;
    /// Lookup an object within this context. Once this function returns, no guarantees are made
    /// about if the object remains mapped as is.
    fn lookup_object(&self, info: Self::MappingInfo) -> Option<ObjectContextInfo>;
    /// As [Self::lookup_object], but yielding only the object. Callers that want nothing else pay
    /// one `ObjectRef` clone instead of the two an [ObjectContextInfo] costs them.
    fn lookup_object_ref(&self, info: Self::MappingInfo) -> Option<ObjectRef>;
    /// Remove an object from the context.
    fn remove_object(&self, info: Self::MappingInfo);
}

/// A struct containing information about how an object is inserted within a context.
#[derive(Clone)]
pub struct ObjectContextInfo {
    object: ObjectRef,
    perms: Protections,
    cache: CacheType,
    flags: MapFlags,
    /// Security context to install the mapping in; zero means the calling thread's active one.
    target_sctx: ObjID,
}

impl ObjectContextInfo {
    pub fn new(object: ObjectRef, perms: Protections, cache: CacheType, flags: MapFlags) -> Self {
        Self::new_in_sctx(object, perms, cache, flags, ObjID::new(0))
    }

    pub fn new_in_sctx(
        object: ObjectRef,
        perms: Protections,
        cache: CacheType,
        flags: MapFlags,
        target_sctx: ObjID,
    ) -> Self {
        Self {
            object,
            perms,
            cache,
            flags,
            target_sctx,
        }
    }

    /// The security context the mapping should go into, or zero for the active one.
    pub fn target_sctx(&self) -> ObjID {
        self.target_sctx
    }

    /// The object.
    pub fn object(&self) -> &ObjectRef {
        &self.object
    }

    /// The protections.
    pub fn prot(&self) -> Protections {
        self.perms
    }

    /// The caching type.
    pub fn cache(&self) -> CacheType {
        self.cache
    }
}

/// A trait for kernel-related memory context actions.
pub trait KernelMemoryContext {
    type Handle<T>: KernelObjectHandle<T>;
    /// Called once during initialization, after which calls to the other function in this trait may
    /// be called.
    fn init_allocator(&self);
    /// Allocate a contiguous chunk of memory. This is not expected to be good for small
    /// allocations, this should be used to grab large chunks of memory to then serve pieces of
    /// using an actual allocator. Returns a pointer to the allocated memory and the size of the
    /// allocation (must be greater than layout's size).
    fn allocate_chunk(&self, layout: Layout) -> Result<NonNull<u8>, TwzError>;
    /// Deallocate a previously allocated chunk.
    ///
    /// # Safety
    /// The call must ensure that the passed in pointer came from a call to [Self::allocate_chunk]
    /// and has the same layout data as was passed to that allocation call.
    unsafe fn deallocate_chunk(&self, layout: Layout, ptr: NonNull<u8>);
    /// Called once after all secondary processors have been booted and are waiting at their main
    /// barrier. Should finish any setup needed in the kernel context before all CPUs can freely
    /// use this context.
    fn prep_smp(&self);
    /// Insert object into kernel space. The context need only support a small number of
    /// kernel-memory-mapped objects. The mapping is released when the returned handle is
    /// dropped.
    fn insert_kernel_object<T>(&self, info: ObjectContextInfo) -> Self::Handle<T>;
}

pub trait KernelObjectHandle<T> {
    fn base(&self) -> &T;
    fn base_mut(&mut self) -> &mut T;
    fn lea_raw<R>(&self, iptr: *const R) -> Option<&R>;
    fn lea_raw_mut<R>(&self, iptr: *mut R) -> Option<&mut R>;
}

pub type KernelObject<T> = KernelObjectVirtHandle<T>;

static KERNEL_CONTEXT: Once<ContextRef> = Once::new();

/// Return a reference to the kernel context. The kernel context is the default context that a
/// thread is in if it's not a userland thread. It's the main context used during init and during
/// secondary processor initialization. It may be used to manipulate kernel memory mappings the same
/// as any other context.
pub fn kernel_context() -> &'static ContextRef {
    KERNEL_CONTEXT.call_once(|| {
        let c = virtmem::VirtContext::new_kernel();
        c.init_kernel_context();
        c
    })
}

/// Census of kernel-object mapping traffic — the emitters behind the full+global TLB broadcasts
/// (`lock_with_consist` hands every kernel-range cursor a `Consistency::new_full_global`, so each
/// of these ops costs a machine-wide whole-TLB flush; measured ~261 per spawn, mapsplit3).
/// Per-site so the fix targets the actual population. Gated; ships OFF.
pub mod kobjcensus {
    use core::sync::atomic::{AtomicU64, Ordering};

    pub const KOBJ_CENSUS: bool = false;

    #[derive(Clone, Copy)]
    #[repr(usize)]
    pub enum Site {
        /// `security.rs` capability verification: per-kuid `VerifyingKey` insert.
        VerifyKey = 0,
        /// `security.rs` sctx-base insert.
        SctxBase,
        /// `obj/control.rs` `ControlObjectCacher` (large-base control objects).
        Control,
        /// `queue.rs` kernel queue mapping.
        Queue,
        /// `interrupt.rs` device wait-word mapping.
        Interrupt,
        /// `KernelObjectVirtHandle::drop` — the unmap side of all of the above.
        Drop,
        /// `lock_with_consist` choosing full+global (every kernel-cursor op, map or unmap).
        FgConsist,
    }
    pub const NR: usize = Site::FgConsist as usize + 1;
    pub const NAMES: [&str; NR] = ["vkey", "sctx", "ctl", "queue", "int", "drop", "fg_consist"];

    static COUNTS: [AtomicU64; NR] = [const { AtomicU64::new(0) }; NR];

    #[inline(always)]
    pub fn record(site: Site) {
        if !KOBJ_CENSUS {
            return;
        }
        COUNTS[site as usize].fetch_add(1, Ordering::Relaxed);
    }

    pub fn snapshot() -> [u64; NR] {
        let mut out = [0u64; NR];
        if !KOBJ_CENSUS {
            return out;
        }
        for (i, c) in COUNTS.iter().enumerate() {
            out[i] = c.load(Ordering::Relaxed);
        }
        out
    }
}
