[alias]
xtask = "run --release --target-dir=.target-xtask --package xtask --"
build-all = "run --release --target-dir=.target-xtask --package xtask -- build"
doc-all = "run --release --target-dir=.target-xtask --package xtask -- doc"
check-all = "run --release --target-dir=.target-xtask --package xtask -- check"
make-image = "run --release --target-dir=.target-xtask --package xtask -- make-image"
start-qemu = "run --release --target-dir=.target-xtask --package xtask -- start-qemu"
bootstrap = "run --release --target-dir=.target-xtask --package xtask -- bootstrap"


[build]
rustdocflags = "-Zunstable-options --enable-index-page"
rustflags = ["--cfg", "curve25519_dalek_backend=\"serial\""]
[env]
PROJECT_NAME_FOR_VERSION_STRING = "twizzler uucoreutils"
