[package]
name = "wasmtest"
version = "0.1.0"
edition = "2021"   

[dependencies]
anyhow = { version = "1.0.93", default-features = false }
wasmtime = {version = "36.0.2", default-features = false, features = ['runtime']}
embedding = { path = "../embedding" }
