[package]
name = "embedding"
version = "0.1.0"
edition = "2021"   


# [lints]
# workspace = true

[dependencies]
anyhow = { version = "1.0.93", default-features = false }

# Note that default-features of wasmtime are disabled and only those required
# are enabled, in this case compilation is done in the guest from the wasm text
# format so `cranelift` and `wat` are enabled.
# wasmtime = { workspace = true,  }
wasmtime = {version = "36.0.2", default-features = false, features = ['runtime']}


[lib]
crate-type = ['staticlib']
test = false
doctest = false
