[package]
name = "sec-test"
version = "0.1.0"
edition = "2021"

[dependencies]
twizzler-abi = {path = "../../lib/twizzler-abi"}
twizzler-security = {path = "../../lib/twizzler-security", features = ["user", "log"]}

twizzler = { path = "../../lib/twizzler" }
twizzler-rt-abi = "0.99"
clap = "4.5.28"
getrandom = "0.2"
colog = "1.3.0"
log = "0.4.27"


